name: Check if License-3rdparty is up to date on PR

on: [pull_request, push]
permissions:
  contents: read

jobs:
  license-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Installing modvendor tool
        run: go install github.com/goware/modvendor@latest
      - name: Installing wwhrd tool
        run: go install github.com/frapposelli/wwhrd@latest
      - name: Installing go-license-detector tool
        run: GO111MODULE=on go install github.com/go-enry/go-license-detector/v4/cmd/license-detector@latest
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.9.12"
          cache: "pip"
      - name: Install dependencies
        run: python3 -m pip install -r .github/scripts/lint-licenses/requirements.txt
      - name: Run license lint task
        run: inv -r .github/scripts/lint-licenses -e lint-licenses

